name: pubgapi
description: A Playerunknown's Battleground API wrapper for Dart!
version: 0.0.5
author: Gacnt <https://github.com/Gacnt>
homepage: https://github.com/Gacnt/Dart-PUBGAPI

environment:
  sdk: '>=1.20.1 <=2.0.0' 

dependencies:
  http: ^0.11.3+16
  json_annotation: ^0.2.3

dev_dependencies:
  json_serializable: ^0.5.0
  test: ^0.12.0
  build_runner: ^0.8.8 
